name: test
description: Greet someone

inputs:
    token:
        description: "GitHub token"
        required: false
        default: ${{ secrets.GITHUB_TOKEN }}

runs:
    using: "node12"
    main: "dist/index.js"
