name: remind review
on: [push, pull_request]

jobs:
    send_pull_requests:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - name: listPullRequests
              uses: GithubActionTastingOrg/AutoMergeMaster@v1.2
              id: list
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
            - name: output
              run: echo '${{ steps.list.outputs.pulls }}'
