name: Enforce timeout-minutes

on: [push, pull_request]

jobs:
    enforce-timeout-minutes:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Enforce timeout-minutes
              uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0
