on: [push, pull_request]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - name: Hello world action step
              id: hello
              uses: GithubActionTastingOrg/AutoMergeMaster@v1.2
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
            - name: Get the output time
                run: echo "Pulls is ${{ steps.hello.outputs.pulls }}"
