on: [push, pull_request]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - name: Hello world action step
              uses: GithubActionTastingOrg/AutoMergeMaster@v1.2
              id: list
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
                  labels: '["WFR"]'
                  skip_hour: "24"
            - name: output
              run: echo '${{ steps.list.outputs.pulls }}'
